language: java
install: skip

os: linux
dist: trusty
jdk: openjdk8

env:
  global:
    DOCKER_REPO=brunoribca/cryptoinsights

jobs:
  include:
    - stage: build
      script: ./gradlew build && ./gradlew bootBuildImage --imageName=$DOCKER_REPO
    - stage: docker push
      if: branch = main
      script: ./docker_push.sh