language: java
install: skip

os: linux
dist: trusty
jdk: openjdk8

env:
  global:
    DOCKER_REPO=brunoribca/cryptoinsights

jobs:
  include:
    - stage: build
      script: ./build.sh

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: main